// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyim9p3cHa5BDl4zbKR1QTayItwnuVPCw',
    appId: '1:245401785677:web:9cd6f9236748240b88d304',
    messagingSenderId: '245401785677',
    projectId: 'gebeya-22f67',
    authDomain: 'gebeya-22f67.firebaseapp.com',
    storageBucket: 'gebeya-22f67.firebasestorage.app',
    measurementId: 'G-8NR35WF6P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qJZkNV62GA7xie93GX_Rr-c-UedIbsY',
    appId: '1:245401785677:android:3db71ad83e08706888d304',
    messagingSenderId: '245401785677',
    projectId: 'gebeya-22f67',
    storageBucket: 'gebeya-22f67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHKcCbNf9H9Tk0Pfcw3mTVVH0IzO3J1-o',
    appId: '1:245401785677:ios:070fb9406885910e88d304',
    messagingSenderId: '245401785677',
    projectId: 'gebeya-22f67',
    storageBucket: 'gebeya-22f67.firebasestorage.app',
    iosBundleId: 'com.example.gebeya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHKcCbNf9H9Tk0Pfcw3mTVVH0IzO3J1-o',
    appId: '1:245401785677:ios:070fb9406885910e88d304',
    messagingSenderId: '245401785677',
    projectId: 'gebeya-22f67',
    storageBucket: 'gebeya-22f67.firebasestorage.app',
    iosBundleId: 'com.example.gebeya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyim9p3cHa5BDl4zbKR1QTayItwnuVPCw',
    appId: '1:245401785677:web:bc556dd7b5b843bc88d304',
    messagingSenderId: '245401785677',
    projectId: 'gebeya-22f67',
    authDomain: 'gebeya-22f67.firebaseapp.com',
    storageBucket: 'gebeya-22f67.firebasestorage.app',
    measurementId: 'G-YFF50964CL',
  );
}
